// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const vehicleCount = `-- name: VehicleCount :one
SELECT COUNT(*) AS total
FROM vehicles
`

func (q *Queries) VehicleCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, vehicleCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const vehiclesByMake = `-- name: VehiclesByMake :many

SELECT make, COUNT(*) AS vehicle_count
FROM vehicles
GROUP BY make
ORDER BY vehicle_count DESC, make ASC
`

type VehiclesByMakeRow struct {
	Make         string `json:"make"`
	VehicleCount int64  `json:"vehicle_count"`
}

// Catalog summary queries (read-side, sqlc-generated). These feed the
// catalog-summary Refresher's derived cache: counts are cheap to recompute and
// only one replica needs to do it (patterns.Mutex in internal/catalogsummary).
func (q *Queries) VehiclesByMake(ctx context.Context) ([]VehiclesByMakeRow, error) {
	rows, err := q.db.Query(ctx, vehiclesByMake)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehiclesByMakeRow
	for rows.Next() {
		var i VehiclesByMakeRow
		if err := rows.Scan(&i.Make, &i.VehicleCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
