// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Lot struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Price struct {
	VehicleID   pgtype.UUID        `json:"vehicle_id"`
	AmountCents int64              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Vehicle struct {
	ID        pgtype.UUID        `json:"id"`
	Vin       string             `json:"vin"`
	Make      string             `json:"make"`
	Model     string             `json:"model"`
	Year      int32              `json:"year"`
	Color     string             `json:"color"`
	LotID     pgtype.UUID        `json:"lot_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
